# Generated by Django 5.1.4 on 2026-10-01 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Nom complet du client.', max_length=150, verbose_name='Nom complet')),
                ('company', models.CharField(blank=True, help_text='Nom de la société (optionnel).', max_length=150, verbose_name='Société')),
                ('email', models.EmailField(help_text='Adresse email du client.', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Numéro de téléphone du client.', max_length=20, verbose_name='Téléphone')),
                ('service_type', models.CharField(help_text='Type de service demandé.', max_length=100, verbose_name='Type de service')),
                ('departure', models.CharField(help_text='Ville ou pays de départ.', max_length=150, verbose_name='Départ')),
                ('destination', models.CharField(help_text='Ville ou pays de destination.', max_length=150, verbose_name='Destination')),
                ('message', models.TextField(blank=True, help_text="Détails supplémentaires sur l'expédition.", verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_review', "En cours d'étude"), ('quoted', 'Devis envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('archived', 'Archivé')], db_index=True, default='new', help_text='Statut actuel de la demande de devis.', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes internes (non visibles par le client).', verbose_name='Notes admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='devis_status_created_idx'), models.Index(fields=['email'], name='devis_email_idx')],
            },
        ),
    ]
