# Generated by Django 5.1.4 on 2026-09-30 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Main title of the campaign.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the offer.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('limited', 'Limited Offer'), ('upcoming', 'Upcoming'), ('expired', 'Expired')], default='active', max_length=20)),
                ('valid_until', models.DateField(help_text='Expiration date for the offer.')),
                ('is_published', models.BooleanField(default=True, help_text='Toggle to hide/show on website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(help_text='Category (e.g., Logistique portuaire)', max_length=100)),
                ('badge', models.CharField(help_text='Badge text (e.g., Bundle, Nouveau)', max_length=50)),
            ],
            options={
                'verbose_name': 'Associated Campaign',
                'verbose_name_plural': 'Associated Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaritimeCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Main title of the campaign.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the offer.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('limited', 'Limited Offer'), ('upcoming', 'Upcoming'), ('expired', 'Expired')], default='active', max_length=20)),
                ('valid_until', models.DateField(help_text='Expiration date for the offer.')),
                ('is_published', models.BooleanField(default=True, help_text='Toggle to hide/show on website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtitle', models.CharField(help_text='Subtitle (e.g., Ligne Europe - Algérie)', max_length=200)),
                ('route_from', models.CharField(help_text='Departure point (e.g., Marseille / Gênes)', max_length=150)),
                ('route_to', models.CharField(help_text='Arrival point (e.g., Alger / Béjaïa)', max_length=150)),
                ('discount', models.CharField(help_text="Discount text (e.g., '-15%')", max_length=50)),
                ('highlights', models.TextField(help_text='List of bullet points. Enter one per line.')),
            ],
            options={
                'verbose_name': 'Maritime Campaign',
                'verbose_name_plural': 'Maritime Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL slug for the service.', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField(help_text='Brief description for cards.')),
                ('long_intro', models.TextField(help_text='Introduction text on detail page.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('benefits', models.TextField(help_text='One benefit per line.')),
                ('why_us', models.TextField(help_text='One reason per line.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order priority.')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('suffix', models.CharField(blank=True, help_text="e.g. '+' or '%'", max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustedPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trusted Partner',
                'verbose_name_plural': 'Trusted Partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Step',
                'verbose_name_plural': 'Service Steps',
                'ordering': ['order'],
            },
        ),
    ]
