# Generated by Django 5.1.4 on 2026-10-01 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(db_index=True, help_text='Unique tracking number for the shipment.', max_length=50, unique=True, verbose_name='Numéro de suivi')),
                ('sender_name', models.CharField(max_length=150, verbose_name="Nom de l'expéditeur")),
                ('sender_address', models.TextField(verbose_name="Adresse de l'expéditeur")),
                ('sender_phone', models.CharField(max_length=20, verbose_name="Téléphone de l'expéditeur")),
                ('receiver_name', models.CharField(max_length=150, verbose_name='Nom du destinataire')),
                ('receiver_address', models.TextField(verbose_name='Adresse du destinataire')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='Téléphone du destinataire')),
                ('transport_mode', models.CharField(choices=[('sea', 'Maritime'), ('air', 'Aérien'), ('road', 'Routier'), ('rail', 'Ferroviaire')], db_index=True, default='sea', max_length=20, verbose_name='Mode de transport')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('picked_up', 'Ramassé'), ('in_transit', 'En transit'), ('at_warehouse', "À l'entrepôt"), ('out_for_delivery', 'En livraison'), ('delivered', 'Livré'), ('cancelled', 'Annulé'), ('exception', 'Exception')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids (kg)')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Longueur (cm)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largeur (cm)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hauteur (cm)')),
                ('origin_city', models.CharField(db_index=True, max_length=100, verbose_name="Ville d'origine")),
                ('origin_country', models.CharField(max_length=100, verbose_name="Pays d'origine")),
                ('destination_city', models.CharField(db_index=True, max_length=100, verbose_name='Ville de destination')),
                ('destination_country', models.CharField(max_length=100, verbose_name='Pays de destination')),
                ('estimated_pickup', models.DateField(blank=True, null=True, verbose_name='Date de ramassage estimée')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Date de livraison estimée')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison réelle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Fragile')),
                ('is_insured', models.BooleanField(default=False, verbose_name='Assuré')),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur déclarée')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('customer', models.ForeignKey(help_text='Customer who owns this shipment.', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Expédition',
                'verbose_name_plural': 'Expéditions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_number', models.CharField(max_length=50, verbose_name='Numéro de colis')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids (kg)')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Longueur (cm)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largeur (cm)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hauteur (cm)')),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur déclarée')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Fragile')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shipping.shipment', verbose_name='Expédition')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
                'ordering': ['package_number'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('picked_up', 'Ramassé'), ('in_transit', 'En transit'), ('at_warehouse', "À l'entrepôt"), ('out_for_delivery', 'En livraison'), ('delivered', 'Livré'), ('cancelled', 'Annulé'), ('exception', 'Exception')], max_length=20, verbose_name='Statut')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipping.shipment', verbose_name='Expédition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Événement de suivi',
                'verbose_name_plural': 'Événements de suivi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'created_at'], name='shipment_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['customer', 'status'], name='shipment_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['origin_city', 'destination_city'], name='shipment_route_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('shipment', 'package_number')},
        ),
    ]
