# Generated by Django 5.1.4 on 2026-10-01 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Client's full name.", max_length=150, verbose_name='Full Name')),
                ('company', models.CharField(blank=True, help_text='Company name (optional).', max_length=150, verbose_name='Company')),
                ('email', models.EmailField(help_text="Client's email address.", max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text="Client's phone number.", max_length=20, verbose_name='Phone')),
                ('service_type', models.CharField(help_text='Type of service requested.', max_length=100, verbose_name='Service Type')),
                ('departure', models.CharField(help_text='City or country of departure.', max_length=150, verbose_name='Departure')),
                ('destination', models.CharField(help_text='City or country of destination.', max_length=150, verbose_name='Destination')),
                ('message', models.TextField(blank=True, help_text='Additional details about the shipment.', verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='new', help_text='Current status of the quotation request.', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to client).', verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='quotation_status_created_idx'), models.Index(fields=['email'], name='quotation_email_idx')],
            },
        ),
    ]
